// const stations = [
//     // Manhattan Stations
//     { name: "Times Square - 42nd Street", coordinates: [40.755, -73.986], lines: ["1", "2", "3", "7", "N", "Q", "R", "W", "S"] },
//     { name: "Grand Central Terminal", coordinates: [40.752, -73.977], lines: ["4", "5", "6", "7", "S"] },
//     { name: "Penn Station", coordinates: [40.750, -73.993], lines: ["1", "2", "3", "A", "C", "E"] },
//     { name: "Union Square", coordinates: [40.735, -73.991], lines: ["4", "5", "6", "L", "N", "Q", "R", "W"] },
//     { name: "Columbus Circle", coordinates: [40.768, -73.982], lines: ["1", "2", "A", "B", "C", "D"] },
//     { name: "Fulton Street", coordinates: [40.710, -74.009], lines: ["2", "3", "4", "5", "A", "C", "J", "Z"] },
//     { name: "Chambers Street", coordinates: [40.714, -74.009], lines: ["1", "2", "3", "A", "C"] },
//     { name: "14th Street", coordinates: [40.737, -73.997], lines: ["1", "2", "3", "F", "M", "L"] },
//     { name: "34th Street - Herald Square", coordinates: [40.750, -73.988], lines: ["B", "D", "F", "M", "N", "Q", "R", "W"] },
//     { name: "59th Street - Columbus Circle", coordinates: [40.768, -73.982], lines: ["1", "A", "B", "C", "D"] },
//     
//     // Brooklyn Stations
//     { name: "Atlantic Avenue - Barclays Center", coordinates: [40.684, -73.977], lines: ["2", "3", "4", "5", "B", "D", "N", "Q", "R"] },
//     { name: "Jay Street - MetroTech", coordinates: [40.692, -73.987], lines: ["A", "C", "F", "R"] },
//     { name: "DeKalb Avenue", coordinates: [40.690, -73.982], lines: ["B", "Q", "R"] },
//     
//     // Queens Stations
//     { name: "Queensboro Plaza", coordinates: [40.750, -73.940], lines: ["7", "N", "W"] },
//     { name: "Jackson Heights - Roosevelt Avenue", coordinates: [40.746, -73.891], lines: ["7", "E", "F", "M", "R"] },
//     { name: "Forest Hills - 71st Avenue", coordinates: [40.721, -73.844], lines: ["E", "F", "M", "R"] },
//     
//     // Bronx Stations
//     { name: "Yankee Stadium", coordinates: [40.828, -73.926], lines: ["4", "B", "D"] },
//     { name: "Fordham Road", coordinates: [40.861, -73.901], lines: ["4", "B", "D"] },
//     
//     // Staten Island Stations
//     { name: "St. George", coordinates: [40.643, -74.075], lines: ["SIR"] }
// ]; 



const stations = [
    // Manhattan Stations
    { name: "Times Square - 42nd Street", coordinates: [40.755, -73.986], lines: ["1", "2", "3", "7", "N", "Q", "R", "W", "S"], pptLink: "https://mta.info/stations/times-square-42nd-st/presentation.pptx" },
    { name: "Grand Central Terminal", coordinates: [40.752, -73.977], lines: ["4", "5", "6", "7", "S"], pptLink: "https://mta.info/stations/grand-central/presentation.pptx" },
    { name: "Penn Station", coordinates: [40.750, -73.993], lines: ["1", "2", "3", "A", "C", "E"], pptLink: "https://mta.info/stations/penn-station/presentation.pptx" },
    { name: "Union Square", coordinates: [40.735, -73.991], lines: ["4", "5", "6", "L", "N", "Q", "R", "W"], pptLink: "https://mta.info/stations/union-square/presentation.pptx" },
    { name: "Columbus Circle", coordinates: [40.768, -73.982], lines: ["1", "2", "A", "B", "C", "D"], pptLink: "https://mta.info/stations/columbus-circle/presentation.pptx" },
    { name: "Fulton Street", coordinates: [40.710, -74.009], lines: ["2", "3", "4", "5", "A", "C", "J", "Z"], pptLink: "https://mta.info/stations/fulton-st/presentation.pptx" },
    { name: "Chambers Street", coordinates: [40.714, -74.009], lines: ["1", "2", "3", "A", "C"], pptLink: "https://mta.info/stations/chambers-st/presentation.pptx" },
    { name: "14th Street", coordinates: [40.737, -73.997], lines: ["1", "2", "3", "F", "M", "L"], pptLink: "https://mta.info/stations/14th-st/presentation.pptx" },
    { name: "34th Street - Herald Square", coordinates: [40.750, -73.988], lines: ["B", "D", "F", "M", "N", "Q", "R", "W"], pptLink: "https://mta.info/stations/34th-st-herald-sq/presentation.pptx" },
    { name: "59th Street - Columbus Circle", coordinates: [40.768, -73.982], lines: ["1", "A", "B", "C", "D"], pptLink: "https://mta.info/stations/59th-st-columbus-circle/presentation.pptx" },
    { name: "125th Street (Lexington Ave)", coordinates: [40.804, -73.937], lines: ["4", "5", "6"], pptLink: "https://mta.info/stations/125th-st-lex/presentation.pptx" },
    { name: "86th Street (Lexington Ave)", coordinates: [40.779, -73.955], lines: ["4", "5", "6"], pptLink: "https://mta.info/stations/86th-st-lex/presentation.pptx" },
    { name: "Wall Street", coordinates: [40.707, -74.011], lines: ["2", "3"], pptLink: "https://mta.info/stations/wall-st/presentation.pptx" },
    { name: "Bowling Green", coordinates: [40.705, -74.014], lines: ["4", "5"], pptLink: "https://mta.info/stations/bowling-green/presentation.pptx" },
    { name: "South Ferry", coordinates: [40.702, -74.013], lines: ["1"], pptLink: "https://mta.info/stations/south-ferry/presentation.pptx" },
    { name: "Canal Street", coordinates: [40.719, -74.001], lines: ["1", "6", "J", "N", "Q", "R", "W", "Z"], pptLink: "https://mta.info/stations/canal-st/presentation.pptx" },
    { name: "World Trade Center", coordinates: [40.713, -74.009], lines: ["E"], pptLink: "https://mta.info/stations/world-trade-center/presentation.pptx" },
    { name: "23rd Street", coordinates: [40.744, -73.996], lines: ["1", "6", "F", "M"], pptLink: "https://mta.info/stations/23rd-st/presentation.pptx" },
    { name: "28th Street", coordinates: [40.745, -73.988], lines: ["1", "6"], pptLink: "https://mta.info/stations/28th-st/presentation.pptx" },
    { name: "50th Street", coordinates: [40.761, -73.984], lines: ["1", "C", "E"], pptLink: "https://mta.info/stations/50th-st/presentation.pptx" },
    { name: "72nd Street", coordinates: [40.779, -73.982], lines: ["1", "2", "3"], pptLink: "https://mta.info/stations/72nd-st/presentation.pptx" },
    { name: "96th Street", coordinates: [40.793, -73.972], lines: ["1", "2", "3", "6"], pptLink: "https://mta.info/stations/96th-st/presentation.pptx" },
    { name: "110th Street", coordinates: [40.800, -73.945], lines: ["6"], pptLink: "https://mta.info/stations/110th-st/presentation.pptx" },
    { name: "116th Street", coordinates: [40.805, -73.949], lines: ["6"], pptLink: "https://mta.info/stations/116th-st/presentation.pptx" },
    { name: "137th Street", coordinates: [40.814, -73.953], lines: ["1"], pptLink: "https://mta.info/stations/137th-st/presentation.pptx" },
    { name: "145th Street", coordinates: [40.820, -73.936], lines: ["1", "3"], pptLink: "https://mta.info/stations/145th-st/presentation.pptx" },
    { name: "168th Street", coordinates: [40.840, -73.940], lines: ["1", "A", "C"], pptLink: "https://mta.info/stations/168th-st/presentation.pptx" },
    { name: "175th Street", coordinates: [40.847, -73.912], lines: ["A"], pptLink: "https://mta.info/stations/175th-st/presentation.pptx" },
    { name: "181st Street", coordinates: [40.849, -73.903], lines: ["1"], pptLink: "https://mta.info/stations/181st-st/presentation.pptx" },
    { name: "191st Street", coordinates: [40.855, -73.898], lines: ["1"], pptLink: "https://mta.info/stations/191st-st/presentation.pptx" },
    { name: "207th Street", coordinates: [40.864, -73.919], lines: ["1"], pptLink: "https://mta.info/stations/207th-st/presentation.pptx" },
    { name: "215th Street", coordinates: [40.869, -73.915], lines: ["1"], pptLink: "https://mta.info/stations/215th-st/presentation.pptx" },
    { name: "225th Street", coordinates: [40.874, -73.911], lines: ["1"], pptLink: "https://mta.info/stations/225th-st/presentation.pptx" },
    { name: "238th Street", coordinates: [40.884, -73.901], lines: ["1"], pptLink: "https://mta.info/stations/238th-st/presentation.pptx" },
    { name: "242nd Street", coordinates: [40.888, -73.898], lines: ["1"], pptLink: "https://mta.info/stations/242nd-st/presentation.pptx" },
    
    // Brooklyn Stations
    { name: "Atlantic Avenue - Barclays Center", coordinates: [40.684, -73.977], lines: ["2", "3", "4", "5", "B", "D", "N", "Q", "R"], pptLink: "https://mta.info/stations/atlantic-ave-barclays/presentation.pptx" },
    { name: "Jay Street - MetroTech", coordinates: [40.692, -73.987], lines: ["A", "C", "F", "R"], pptLink: "https://mta.info/stations/jay-st-metrotech/presentation.pptx" },
    { name: "DeKalb Avenue", coordinates: [40.690, -73.982], lines: ["B", "Q", "R"], pptLink: "https://mta.info/stations/dekalb-ave/presentation.pptx" },
    { name: "Coney Island - Stillwell Avenue", coordinates: [40.577, -73.981], lines: ["D", "F", "N", "Q"], pptLink: "https://mta.info/stations/coney-island-stillwell/presentation.pptx" },
    { name: "Brighton Beach", coordinates: [40.578, -73.961], lines: ["B", "Q"], pptLink: "https://mta.info/stations/brighton-beach/presentation.pptx" },
    { name: "Sheepshead Bay", coordinates: [40.587, -73.954], lines: ["B", "Q"], pptLink: "https://mta.info/stations/sheepshead-bay/presentation.pptx" },
    { name: "Kings Highway", coordinates: [40.608, -73.957], lines: ["B", "Q"], pptLink: "https://mta.info/stations/kings-highway/presentation.pptx" },
    { name: "Avenue U", coordinates: [40.599, -73.955], lines: ["B", "Q"], pptLink: "https://mta.info/stations/avenue-u/presentation.pptx" },
    { name: "Neck Road", coordinates: [40.595, -73.955], lines: ["B", "Q"], pptLink: "https://mta.info/stations/neck-road/presentation.pptx" },
    { name: "Bay Ridge - 95th Street", coordinates: [40.617, -74.031], lines: ["R"], pptLink: "https://mta.info/stations/bay-ridge-95th-st/presentation.pptx" },
    { name: "86th Street (Brooklyn)", coordinates: [40.622, -74.028], lines: ["R"], pptLink: "https://mta.info/stations/86th-st-brooklyn/presentation.pptx" },
    { name: "77th Street", coordinates: [40.629, -74.025], lines: ["R"], pptLink: "https://mta.info/stations/77th-st-brooklyn/presentation.pptx" },
    { name: "Prospect Park", coordinates: [40.661, -73.962], lines: ["B", "Q", "S"], pptLink: "https://mta.info/stations/prospect-park/presentation.pptx" },
    { name: "7th Avenue", coordinates: [40.677, -73.973], lines: ["B", "Q"], pptLink: "https://mta.info/stations/7th-ave-brooklyn/presentation.pptx" },
    { name: "Church Avenue", coordinates: [40.644, -73.983], lines: ["B", "Q"], pptLink: "https://mta.info/stations/church-ave-brooklyn/presentation.pptx" },
    { name: "Newkirk Plaza", coordinates: [40.639, -73.982], lines: ["B", "Q"], pptLink: "https://mta.info/stations/newkirk-plaza/presentation.pptx" },
    { name: "Flatbush Avenue - Brooklyn College", coordinates: [40.632, -73.947], lines: ["2", "5"], pptLink: "https://mta.info/stations/flatbush-ave-brooklyn-college/presentation.pptx" },
    { name: "Nostrand Avenue", coordinates: [40.669, -73.950], lines: ["3"], pptLink: "https://mta.info/stations/nostrand-ave/presentation.pptx" },
    { name: "Kingston Avenue", coordinates: [40.669, -73.942], lines: ["3"], pptLink: "https://mta.info/stations/kingston-ave/presentation.pptx" },
    { name: "Crown Heights - Utica Avenue", coordinates: [40.668, -73.932], lines: ["3", "4"], pptLink: "https://mta.info/stations/crown-heights-utica-ave/presentation.pptx" },
    { name: "Sutter Avenue - Rutland Road", coordinates: [40.669, -73.922], lines: ["3"], pptLink: "https://mta.info/stations/sutter-ave-rutland-road/presentation.pptx" },
    { name: "Saratoga Avenue", coordinates: [40.670, -73.916], lines: ["3"], pptLink: "https://mta.info/stations/saratoga-ave/presentation.pptx" },
    { name: "Rockaway Avenue", coordinates: [40.670, -73.911], lines: ["3"], pptLink: "https://mta.info/stations/rockaway-ave/presentation.pptx" },
    { name: "Junius Street", coordinates: [40.663, -73.902], lines: ["3"], pptLink: "https://mta.info/stations/junius-st/presentation.pptx" },
    { name: "Pennsylvania Avenue", coordinates: [40.664, -73.894], lines: ["3"], pptLink: "https://mta.info/stations/pennsylvania-ave/presentation.pptx" },
    { name: "Van Siclen Avenue", coordinates: [40.665, -73.889], lines: ["3"], pptLink: "https://mta.info/stations/van-siclen-ave/presentation.pptx" },
    { name: "New Lots Avenue", coordinates: [40.666, -73.884], lines: ["3"], pptLink: "https://mta.info/stations/new-lots-ave/presentation.pptx" },
    { name: "Livonia Avenue", coordinates: [40.664, -73.900], lines: ["L"], pptLink: "https://mta.info/stations/livonia-ave/presentation.pptx" },
    { name: "Sutter Avenue", coordinates: [40.664, -73.902], lines: ["L"], pptLink: "https://mta.info/stations/sutter-ave-l/presentation.pptx" },
    { name: "Atlantic Avenue", coordinates: [40.675, -73.903], lines: ["L"], pptLink: "https://mta.info/stations/atlantic-ave-l/presentation.pptx" },
    { name: "Broadway Junction", coordinates: [40.679, -73.904], lines: ["A", "C", "J", "L", "Z"], pptLink: "https://mta.info/stations/broadway-junction/presentation.pptx" },
    { name: "Bushwick Avenue - Aberdeen Street", coordinates: [40.682, -73.905], lines: ["L"], pptLink: "https://mta.info/stations/bushwick-ave-aberdeen-st/presentation.pptx" },
    { name: "Myrtle - Wyckoff Avenues", coordinates: [40.699, -73.912], lines: ["L", "M"], pptLink: "https://mta.info/stations/myrtle-wyckoff-aves/presentation.pptx" },
    { name: "Halsey Street", coordinates: [40.695, -73.904], lines: ["L"], pptLink: "https://mta.info/stations/halsey-st/presentation.pptx" },
    { name: "Wilson Avenue", coordinates: [40.689, -73.904], lines: ["L"], pptLink: "https://mta.info/stations/wilson-ave/presentation.pptx" },
    { name: "Jefferson Street", coordinates: [40.707, -73.923], lines: ["L"], pptLink: "https://mta.info/stations/jefferson-st/presentation.pptx" },
    { name: "Morgan Avenue", coordinates: [40.706, -73.933], lines: ["L"], pptLink: "https://mta.info/stations/morgan-ave/presentation.pptx" },
    { name: "Montrose Avenue", coordinates: [40.708, -73.940], lines: ["L"], pptLink: "https://mta.info/stations/montrose-ave/presentation.pptx" },
    { name: "Grand Street", coordinates: [40.712, -73.941], lines: ["L"], pptLink: "https://mta.info/stations/grand-st-brooklyn/presentation.pptx" },
    { name: "Graham Avenue", coordinates: [40.715, -73.944], lines: ["L"], pptLink: "https://mta.info/stations/graham-ave/presentation.pptx" },
    { name: "Lorimer Street", coordinates: [40.714, -73.950], lines: ["L"], pptLink: "https://mta.info/stations/lorimer-st/presentation.pptx" },
    { name: "Bedford Avenue", coordinates: [40.717, -73.957], lines: ["L"], pptLink: "https://mta.info/stations/bedford-ave/presentation.pptx" },
    { name: "1st Avenue", coordinates: [40.721, -73.982], lines: ["L"], pptLink: "https://mta.info/stations/1st-ave/presentation.pptx" },
    { name: "3rd Avenue", coordinates: [40.732, -73.986], lines: ["L"], pptLink: "https://mta.info/stations/3rd-ave/presentation.pptx" },
    
    // Queens Stations
    { name: "Queensboro Plaza", coordinates: [40.750, -73.940], lines: ["7", "N", "W"], pptLink: "https://mta.info/stations/queensboro-plaza/presentation.pptx" },
    { name: "Jackson Heights - Roosevelt Avenue", coordinates: [40.746, -73.891], lines: ["7", "E", "F", "M", "R"], pptLink: "https://mta.info/stations/jackson-heights-roosevelt-ave/presentation.pptx" },
    { name: "Forest Hills - 71st Avenue", coordinates: [40.721, -73.844], lines: ["E", "F", "M", "R"], pptLink: "https://mta.info/stations/forest-hills-71st-ave/presentation.pptx" },
    { name: "Flushing - Main Street", coordinates: [40.760, -73.830], lines: ["7"], pptLink: "https://mta.info/stations/flushing-main-st/presentation.pptx" },
    { name: "74th Street - Broadway", coordinates: [40.747, -73.891], lines: ["7"], pptLink: "https://mta.info/stations/74th-st-broadway/presentation.pptx" },
    { name: "82nd Street - Jackson Heights", coordinates: [40.747, -73.884], lines: ["7"], pptLink: "https://mta.info/stations/82nd-st-jackson-heights/presentation.pptx" },
    { name: "90th Street - Elmhurst", coordinates: [40.748, -73.877], lines: ["7"], pptLink: "https://mta.info/stations/90th-st-elmhurst/presentation.pptx" },
    { name: "103rd Street - Corona Plaza", coordinates: [40.751, -73.863], lines: ["7"], pptLink: "https://mta.info/stations/103rd-st-corona-plaza/presentation.pptx" },
    { name: "111th Street", coordinates: [40.752, -73.855], lines: ["7"], pptLink: "https://mta.info/stations/111th-st/presentation.pptx" },
    { name: "Junction Boulevard", coordinates: [40.754, -73.846], lines: ["7"], pptLink: "https://mta.info/stations/junction-blvd/presentation.pptx" },
    { name: "Sutphin Boulevard - Archer Avenue - JFK Airport", coordinates: [40.700, -73.808], lines: ["E", "J", "Z"], pptLink: "https://mta.info/stations/sutphin-blvd-archer-ave-jfk/presentation.pptx" },
    { name: "Jamaica Center - Parsons/Archer", coordinates: [40.702, -73.801], lines: ["E", "J", "Z"], pptLink: "https://mta.info/stations/jamaica-center-parsons-archer/presentation.pptx" },
    { name: "Howard Beach - JFK Airport", coordinates: [40.660, -73.830], lines: ["A"], pptLink: "https://mta.info/stations/howard-beach-jfk/presentation.pptx" },
    { name: "Aqueduct Racetrack", coordinates: [40.668, -73.835], lines: ["A"], pptLink: "https://mta.info/stations/aqueduct-racetrack/presentation.pptx" },
    { name: "Rockaway Boulevard", coordinates: [40.680, -73.843], lines: ["A"], pptLink: "https://mta.info/stations/rockaway-blvd/presentation.pptx" },
    { name: "Ozone Park - Lefferts Boulevard", coordinates: [40.685, -73.843], lines: ["A"], pptLink: "https://mta.info/stations/ozone-park-lefferts-blvd/presentation.pptx" },
    { name: "Beach 67th Street", coordinates: [40.591, -73.796], lines: ["A"], pptLink: "https://mta.info/stations/beach-67th-st/presentation.pptx" },
    { name: "Beach 60th Street", coordinates: [40.592, -73.788], lines: ["A"], pptLink: "https://mta.info/stations/beach-60th-st/presentation.pptx" },
    { name: "Beach 44th Street", coordinates: [40.593, -73.776], lines: ["A"], pptLink: "https://mta.info/stations/beach-44th-st/presentation.pptx" },
    { name: "Beach 36th Street", coordinates: [40.595, -73.768], lines: ["A"], pptLink: "https://mta.info/stations/beach-36th-st/presentation.pptx" },
    { name: "Beach 25th Street", coordinates: [40.600, -73.762], lines: ["A"], pptLink: "https://mta.info/stations/beach-25th-st/presentation.pptx" },
    { name: "Far Rockaway - Mott Avenue", coordinates: [40.605, -73.755], lines: ["A"], pptLink: "https://mta.info/stations/far-rockaway-mott-ave/presentation.pptx" },
    { name: "Astoria - Ditmars Boulevard", coordinates: [40.775, -73.912], lines: ["N", "W"], pptLink: "https://mta.info/stations/astoria-ditmars-blvd/presentation.pptx" },
    { name: "Astoria Boulevard", coordinates: [40.770, -73.918], lines: ["N", "W"], pptLink: "https://mta.info/stations/astoria-blvd/presentation.pptx" },
    { name: "30th Avenue", coordinates: [40.767, -73.921], lines: ["N", "W"], pptLink: "https://mta.info/stations/30th-ave/presentation.pptx" },
    { name: "Broadway (Queens)", coordinates: [40.761, -73.925], lines: ["N", "W"], pptLink: "https://mta.info/stations/broadway-queens/presentation.pptx" },
    { name: "36th Avenue", coordinates: [40.756, -73.929], lines: ["N", "W"], pptLink: "https://mta.info/stations/36th-ave/presentation.pptx" },
    { name: "39th Avenue", coordinates: [40.753, -73.933], lines: ["N", "W"], pptLink: "https://mta.info/stations/39th-ave/presentation.pptx" },
    { name: "Queens Plaza", coordinates: [40.751, -73.937], lines: ["E", "M", "R"], pptLink: "https://mta.info/stations/queens-plaza/presentation.pptx" },
    { name: "Court Square - 23rd Street", coordinates: [40.747, -73.946], lines: ["E", "G", "M", "7"], pptLink: "https://mta.info/stations/court-square-23rd-st/presentation.pptx" },
    { name: "21st Street - Queensbridge", coordinates: [40.754, -73.942], lines: ["F"], pptLink: "https://mta.info/stations/21st-st-queensbridge/presentation.pptx" },
    { name: "Roosevelt Island", coordinates: [40.759, -73.953], lines: ["F"], pptLink: "https://mta.info/stations/roosevelt-island/presentation.pptx" },
    { name: "Lexington Avenue/59th Street", coordinates: [40.763, -73.966], lines: ["F", "N", "R", "W"], pptLink: "https://mta.info/stations/lexington-ave-59th-st/presentation.pptx" },
    { name: "5th Avenue/59th Street", coordinates: [40.765, -73.976], lines: ["N", "R", "W"], pptLink: "https://mta.info/stations/5th-ave-59th-st/presentation.pptx" },
    { name: "57th Street - 7th Avenue", coordinates: [40.765, -73.981], lines: ["N", "Q", "R", "W"], pptLink: "https://mta.info/stations/57th-st-7th-ave/presentation.pptx" },
    { name: "49th Street", coordinates: [40.760, -73.984], lines: ["N", "R", "W"], pptLink: "https://mta.info/stations/49th-st/presentation.pptx" },
    
    // Bronx Stations
    { name: "Yankee Stadium", coordinates: [40.828, -73.926], lines: ["4", "B", "D"], pptLink: "https://mta.info/stations/yankee-stadium/presentation.pptx" },
    { name: "Fordham Road", coordinates: [40.861, -73.901], lines: ["4", "B", "D"], pptLink: "https://mta.info/stations/fordham-road/presentation.pptx" },
    { name: "161st Street - Yankee Stadium", coordinates: [40.828, -73.926], lines: ["4", "B", "D"], pptLink: "https://mta.info/stations/161st-st-yankee-stadium/presentation.pptx" },
    { name: "167th Street", coordinates: [40.833, -73.918], lines: ["4"], pptLink: "https://mta.info/stations/167th-st/presentation.pptx" },
    { name: "170th Street", coordinates: [40.840, -73.914], lines: ["4"], pptLink: "https://mta.info/stations/170th-st/presentation.pptx" },
    { name: "174th Street", coordinates: [40.845, -73.910], lines: ["4"], pptLink: "https://mta.info/stations/174th-st/presentation.pptx" },
    { name: "Burnside Avenue", coordinates: [40.853, -73.907], lines: ["4"], pptLink: "https://mta.info/stations/burnside-ave/presentation.pptx" },
    { name: "183rd Street", coordinates: [40.858, -73.900], lines: ["4"], pptLink: "https://mta.info/stations/183rd-st/presentation.pptx" },
    { name: "Kingsbridge Road", coordinates: [40.867, -73.897], lines: ["4"], pptLink: "https://mta.info/stations/kingsbridge-road/presentation.pptx" },
    { name: "Bedford Park Boulevard - Lehman College", coordinates: [40.873, -73.890], lines: ["4"], pptLink: "https://mta.info/stations/bedford-park-blvd-lehman-college/presentation.pptx" },
    { name: "Mosholu Parkway", coordinates: [40.879, -73.885], lines: ["4"], pptLink: "https://mta.info/stations/mosholu-parkway/presentation.pptx" },
    { name: "Woodlawn", coordinates: [40.886, -73.879], lines: ["4"], pptLink: "https://mta.info/stations/woodlawn/presentation.pptx" },
    { name: "East 180th Street", coordinates: [40.842, -73.873], lines: ["2", "5"], pptLink: "https://mta.info/stations/east-180th-st/presentation.pptx" },
    { name: "West Farms Square - East Tremont Avenue", coordinates: [40.840, -73.880], lines: ["2", "5"], pptLink: "https://mta.info/stations/west-farms-sq-east-tremont-ave/presentation.pptx" },
    { name: "174th Street", coordinates: [40.837, -73.887], lines: ["2", "5"], pptLink: "https://mta.info/stations/174th-st-bronx/presentation.pptx" },
    { name: "Freeman Street", coordinates: [40.833, -73.893], lines: ["2", "5"], pptLink: "https://mta.info/stations/freeman-st/presentation.pptx" },
    { name: "Simpson Street", coordinates: [40.824, -73.893], lines: ["2", "5"], pptLink: "https://mta.info/stations/simpson-st/presentation.pptx" },
    { name: "Intervale Avenue", coordinates: [40.822, -73.897], lines: ["2", "5"], pptLink: "https://mta.info/stations/intervale-ave/presentation.pptx" },
    { name: "Prospect Avenue", coordinates: [40.819, -73.901], lines: ["2", "5"], pptLink: "https://mta.info/stations/prospect-ave-bronx/presentation.pptx" },
    { name: "Jackson Avenue", coordinates: [40.816, -73.907], lines: ["2", "5"], pptLink: "https://mta.info/stations/jackson-ave/presentation.pptx" },
    { name: "Third Avenue - 149th Street", coordinates: [40.816, -73.917], lines: ["2", "5"], pptLink: "https://mta.info/stations/third-ave-149th-st/presentation.pptx" },
    { name: "149th Street - Grand Concourse", coordinates: [40.818, -73.927], lines: ["2", "4", "5"], pptLink: "https://mta.info/stations/149th-st-grand-concourse/presentation.pptx" },
    { name: "138th Street - Grand Concourse", coordinates: [40.813, -73.929], lines: ["4", "5"], pptLink: "https://mta.info/stations/138th-st-grand-concourse/presentation.pptx" },
    { name: "125th Street", coordinates: [40.811, -73.938], lines: ["4", "5", "6"], pptLink: "https://mta.info/stations/125th-st-bronx/presentation.pptx" },
    { name: "116th Street", coordinates: [40.805, -73.941], lines: ["4", "5", "6"], pptLink: "https://mta.info/stations/116th-st-bronx/presentation.pptx" },
    { name: "110th Street", coordinates: [40.800, -73.944], lines: ["4", "5", "6"], pptLink: "https://mta.info/stations/110th-st-bronx/presentation.pptx" },
    { name: "103rd Street", coordinates: [40.796, -73.947], lines: ["4", "5", "6"], pptLink: "https://mta.info/stations/103rd-st-bronx/presentation.pptx" },
    { name: "96th Street", coordinates: [40.793, -73.949], lines: ["4", "5", "6"], pptLink: "https://mta.info/stations/96th-st-bronx/presentation.pptx" },
    { name: "86th Street", coordinates: [40.786, -73.952], lines: ["4", "5", "6"], pptLink: "https://mta.info/stations/86th-st-bronx/presentation.pptx" },
    { name: "77th Street", coordinates: [40.780, -73.955], lines: ["4", "5", "6"], pptLink: "https://mta.info/stations/77th-st-bronx/presentation.pptx" },
    { name: "68th Street - Hunter College", coordinates: [40.768, -73.958], lines: ["4", "5", "6"], pptLink: "https://mta.info/stations/68th-st-hunter-college/presentation.pptx" },
    { name: "59th Street", coordinates: [40.763, -73.961], lines: ["4", "5", "6"], pptLink: "https://mta.info/stations/59th-st-bronx/presentation.pptx" },
    { name: "51st Street", coordinates: [40.757, -73.964], lines: ["4", "5", "6"], pptLink: "https://mta.info/stations/51st-st-bronx/presentation.pptx" },
    { name: "Grand Central - 42nd Street", coordinates: [40.752, -73.977], lines: ["4", "5", "6", "7", "S"], pptLink: "https://mta.info/stations/grand-central-42nd-st/presentation.pptx" },
    { name: "33rd Street", coordinates: [40.746, -73.982], lines: ["4", "5", "6"], pptLink: "https://mta.info/stations/33rd-st/presentation.pptx" },
    { name: "28th Street", coordinates: [40.741, -73.984], lines: ["4", "5", "6"], pptLink: "https://mta.info/stations/28th-st-bronx/presentation.pptx" },
    { name: "23rd Street", coordinates: [40.736, -73.987], lines: ["4", "5", "6"], pptLink: "https://mta.info/stations/23rd-st-bronx/presentation.pptx" },
    { name: "14th Street - Union Square", coordinates: [40.735, -73.991], lines: ["4", "5", "6", "L", "N", "Q", "R", "W"], pptLink: "https://mta.info/stations/14th-st-union-sq/presentation.pptx" },
    { name: "Astor Place", coordinates: [40.730, -73.992], lines: ["4", "5", "6"], pptLink: "https://mta.info/stations/astor-place/presentation.pptx" },
    { name: "Bleecker Street", coordinates: [40.726, -73.995], lines: ["4", "5", "6"], pptLink: "https://mta.info/stations/bleecker-st/presentation.pptx" },
    { name: "Spring Street", coordinates: [40.722, -73.997], lines: ["4", "5", "6"], pptLink: "https://mta.info/stations/spring-st/presentation.pptx" },
    { name: "Canal Street", coordinates: [40.719, -74.001], lines: ["4", "5", "6", "J", "N", "Q", "R", "W", "Z"], pptLink: "https://mta.info/stations/canal-st-bronx/presentation.pptx" },
    { name: "Brooklyn Bridge - City Hall", coordinates: [40.713, -74.004], lines: ["4", "5", "6"], pptLink: "https://mta.info/stations/brooklyn-bridge-city-hall/presentation.pptx" },
    { name: "Fulton Street", coordinates: [40.710, -74.009], lines: ["2", "3", "4", "5", "A", "C", "J", "Z"], pptLink: "https://mta.info/stations/fulton-st-bronx/presentation.pptx" },
    { name: "Wall Street", coordinates: [40.707, -74.011], lines: ["2", "3"], pptLink: "https://mta.info/stations/wall-st-bronx/presentation.pptx" },
    { name: "Bowling Green", coordinates: [40.705, -74.014], lines: ["4", "5"], pptLink: "https://mta.info/stations/bowling-green-bronx/presentation.pptx" },
    { name: "Borough Hall", coordinates: [40.693, -73.990], lines: ["2", "3", "4", "5"], pptLink: "https://mta.info/stations/borough-hall/presentation.pptx" },
    { name: "Nevins Street", coordinates: [40.688, -73.980], lines: ["2", "3", "4", "5"], pptLink: "https://mta.info/stations/nevins-st/presentation.pptx" },
    { name: "Atlantic Avenue - Barclays Center", coordinates: [40.684, -73.977], lines: ["2", "3", "4", "5", "B", "D", "N", "Q", "R"], pptLink: "https://mta.info/stations/atlantic-ave-barclays-bronx/presentation.pptx" },
    { name: "Bergen Street", coordinates: [40.681, -73.975], lines: ["2", "3"], pptLink: "https://nymta.sharepoint.com/:p:/r/sites/StationMaintenanceAdmin/_layouts/15/Doc.aspx?sourcedoc=%7BB7BC485A-8699-4BBF-A9B5-A49588BC1052%7D&file=Bergen%20St..pptx&action=edit&mobileredirect=true" },
    { name: "Grand Army Plaza", coordinates: [40.675, -73.971], lines: ["2", "3"], pptLink: "https://mta.info/stations/grand-army-plaza/presentation.pptx" },
    { name: "Eastern Parkway - Brooklyn Museum", coordinates: [40.672, -73.964], lines: ["2", "3"], pptLink: "https://mta.info/stations/eastern-parkway-brooklyn-museum/presentation.pptx" },
    { name: "Franklin Avenue - Medgar Evers College", coordinates: [40.669, -73.958], lines: ["2", "3", "4", "5"], pptLink: "https://mta.info/stations/franklin-ave-medgar-evers-college/presentation.pptx" },
    { name: "President Street", coordinates: [40.667, -73.950], lines: ["2", "3"], pptLink: "https://mta.info/stations/president-st/presentation.pptx" },
    { name: "Sterling Street", coordinates: [40.663, -73.950], lines: ["2", "3"], pptLink: "https://mta.info/stations/sterling-st/presentation.pptx" },
    { name: "Winthrop Street", coordinates: [40.660, -73.950], lines: ["2", "3"], pptLink: "https://mta.info/stations/winthrop-st/presentation.pptx" },
    { name: "Church Avenue", coordinates: [40.644, -73.983], lines: ["2", "3", "4", "5"], pptLink: "https://mta.info/stations/church-ave-bronx/presentation.pptx" },
    { name: "Beverley Road", coordinates: [40.644, -73.964], lines: ["2", "3"], pptLink: "https://mta.info/stations/beverley-road/presentation.pptx" },
    { name: "Newkirk Avenue", coordinates: [40.640, -73.963], lines: ["2", "3"], pptLink: "https://mta.info/stations/newkirk-ave/presentation.pptx" },
    { name: "Flatbush Avenue - Brooklyn College", coordinates: [40.632, -73.947], lines: ["2", "3", "4", "5"], pptLink: "https://mta.info/stations/flatbush-ave-brooklyn-college-bronx/presentation.pptx" },
    { name: "Nostrand Avenue", coordinates: [40.669, -73.950], lines: ["3"], pptLink: "https://mta.info/stations/nostrand-ave-bronx/presentation.pptx" },
    { name: "Kingston Avenue", coordinates: [40.669, -73.942], lines: ["3"], pptLink: "https://mta.info/stations/kingston-ave-bronx/presentation.pptx" },
    { name: "Crown Heights - Utica Avenue", coordinates: [40.668, -73.932], lines: ["3", "4"], pptLink: "https://mta.info/stations/crown-heights-utica-ave-bronx/presentation.pptx" },
    { name: "Sutter Avenue - Rutland Road", coordinates: [40.669, -73.922], lines: ["3"], pptLink: "https://mta.info/stations/sutter-ave-rutland-road-bronx/presentation.pptx" },
    { name: "Saratoga Avenue", coordinates: [40.670, -73.916], lines: ["3"], pptLink: "https://mta.info/stations/saratoga-ave-bronx/presentation.pptx" },
    { name: "Rockaway Avenue", coordinates: [40.670, -73.911], lines: ["3"], pptLink: "https://mta.info/stations/rockaway-ave-bronx/presentation.pptx" },
    { name: "Junius Street", coordinates: [40.663, -73.902], lines: ["3"], pptLink: "https://mta.info/stations/junius-st-bronx/presentation.pptx" },
    { name: "Pennsylvania Avenue", coordinates: [40.664, -73.894], lines: ["3"], pptLink: "https://mta.info/stations/pennsylvania-ave-bronx/presentation.pptx" },
    { name: "Van Siclen Avenue", coordinates: [40.665, -73.889], lines: ["3"], pptLink: "https://mta.info/stations/van-siclen-ave-bronx/presentation.pptx" },
    { name: "New Lots Avenue", coordinates: [40.666, -73.884], lines: ["3"], pptLink: "https://mta.info/stations/new-lots-ave-bronx/presentation.pptx" },
    { name: "Livonia Avenue", coordinates: [40.664, -73.900], lines: ["L"], pptLink: "https://mta.info/stations/livonia-ave-bronx/presentation.pptx" },
    { name: "Sutter Avenue", coordinates: [40.664, -73.902], lines: ["L"], pptLink: "https://mta.info/stations/sutter-ave-l-bronx/presentation.pptx" },
    { name: "Atlantic Avenue", coordinates: [40.675, -73.903], lines: ["L"], pptLink: "https://mta.info/stations/atlantic-ave-l-bronx/presentation.pptx" },
    { name: "Broadway Junction", coordinates: [40.679, -73.904], lines: ["A", "C", "J", "L", "Z"], pptLink: "https://mta.info/stations/broadway-junction-bronx/presentation.pptx" },
    { name: "Bushwick Avenue - Aberdeen Street", coordinates: [40.682, -73.905], lines: ["L"], pptLink: "https://mta.info/stations/bushwick-ave-aberdeen-st-bronx/presentation.pptx" },
    { name: "Myrtle - Wyckoff Avenues", coordinates: [40.699, -73.912], lines: ["L", "M"], pptLink: "https://mta.info/stations/myrtle-wyckoff-aves-bronx/presentation.pptx" },
    { name: "Halsey Street", coordinates: [40.695, -73.904], lines: ["L"], pptLink: "https://mta.info/stations/halsey-st-bronx/presentation.pptx" },
    { name: "Wilson Avenue", coordinates: [40.689, -73.904], lines: ["L"], pptLink: "https://mta.info/stations/wilson-ave-bronx/presentation.pptx" },
    { name: "Jefferson Street", coordinates: [40.707, -73.923], lines: ["L"], pptLink: "https://mta.info/stations/jefferson-st-bronx/presentation.pptx" },
    { name: "Morgan Avenue", coordinates: [40.706, -73.933], lines: ["L"], pptLink: "https://mta.info/stations/morgan-ave-bronx/presentation.pptx" },
    { name: "Montrose Avenue", coordinates: [40.708, -73.940], lines: ["L"], pptLink: "https://mta.info/stations/montrose-ave-bronx/presentation.pptx" },
    { name: "Grand Street", coordinates: [40.712, -73.941], lines: ["L"], pptLink: "https://mta.info/stations/grand-st-bronx/presentation.pptx" },
    { name: "Graham Avenue", coordinates: [40.715, -73.944], lines: ["L"], pptLink: "https://mta.info/stations/graham-ave-bronx/presentation.pptx" },
    { name: "Lorimer Street", coordinates: [40.714, -73.950], lines: ["L"], pptLink: "https://mta.info/stations/lorimer-st-bronx/presentation.pptx" },
    { name: "Bedford Avenue", coordinates: [40.717, -73.957], lines: ["L"], pptLink: "https://mta.info/stations/bedford-ave-bronx/presentation.pptx" },
    { name: "1st Avenue", coordinates: [40.721, -73.982], lines: ["L"], pptLink: "https://mta.info/stations/1st-ave-bronx/presentation.pptx" },
    { name: "3rd Avenue", coordinates: [40.732, -73.986], lines: ["L"], pptLink: "https://mta.info/stations/3rd-ave-bronx/presentation.pptx" }
];